### ISSUE TITLE
A package manager to clio

### ISSUE THREAD

**Issue by atakanyenel** [clio-lang/clio-todo#1]
I saw the language in your medium post. Really liked it actually. Importing functions from an endpoint is quite brilliant. Keep up the good work.

I noticed in your todo repo that you are also committing rethinkdb code to repo. That's currently okay because it looks like currently there is no `dependencies` file that clio can download the packages from git or registry. I read that you don't want to work on new features now but you already have the `clio get` command , so if it's a requirement , we can discuss about adding a simple dependency file ( I might work on it) and a `clio install (resolve)`  command that calls `clio get` for packages.

I know how hard it is to write a package manager with different versioning and many packages, but currently a simple one can improve the usability of new clio modules.

**Comment by micheleriva** [comment]
Hi @atakanyenel !
We are currently working on a package manager which is heavily inspired to Go and Hex (Elixir Lang), where you'll be able to run the following commands:

**From GitHub:**
`clio get github.com/foo/bar`
`clio get github.com/foo/bar@0.2.1`

**From Clio Official Repo:**
`clio get foo`
`clio get foo@0.2.1`

**From Package.json:**

```json
{
  ...
  "clioDependencies": [
	"foo",
	"bar@1.2.3",
	"github.com/foo/bar",
	"github.com/bar/foobar@2.2.1"
  ]
}
```

**Comment by atakanyenel** [comment]
Oh nice, looking forward to write clio modules. You can close this issue or keep it open as a tracker for the package manager, up to you :)

**Comment by micheleriva** [comment]
Thank you so much @atakanyenel, we are currently reviewing the Package Manaer, I think it will be ready soon 😄

**Comment by pouya-eghbali** [comment]
Hello @atakanyenel, thanks for showing your interest. I'm planning to fix bugs we currently have and remove some of our unnecessary code, but we're open to suggestions and requests. We'll have a _usable_ Clio soon.

I merged your PR @micheleriva, thanks for the great work! I'll close this issue. If there are any more questions we can discuss in the main repo where the package manager code is hosted.
